### ISSUE TITLE
考虑兼容react 18 吗？

### ISSUE THREAD

**Issue by chunbaiseakuang** [BowenZ/rc-danmaku#4]
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.

在react18项目里引用会导致一直触发警告

**Comment by BowenZ** [comment]
会兼容的，有需求我就提前考虑下

**Comment by newCoderH** [comment]
> 会兼容的，有需求我就提前考虑下

请求兼容react18

**Comment by BowenZ** [comment]
@chunbaiseakuang @newCoderH 已经兼容react18，现在版本号是`rc-danmaku@1.2.0-alpha.2`，我这边用最新的create-react-app测试是正常的，如果后续没有发现bug会更新正式版
